### ISSUE TITLE
Package not working after update

### ISSUE THREAD

**Issue by bigardone** [msaraiva/atom-elixir#19]
Hi!
I've just updated to **v0.1.2** using Atom's package manager and it doesn't show the*\* Documentation Tab*\* anymore. I'm trying to launch it with the `F2` key or the **command palette**, but nothing happens and no errors are shown. Is this only happening to me?
Thanks in advance.

**Comment by msaraiva** [comment]
I've just found out that the package is not deactivating correctly. So I guess updating without restarting will not work. Does the problem persists even after restarting or hitting `CTRL+ALT+CMD+L`?

In case you still having trouble after restarting, hit `ALT+CMD+i` to open the console. You should see something like:
```
[atom-elixir] Initializing alchemist-server for environment "dev" (Elixir version 1.2.0)
```

Check if there's any other message.

Thanks.

**Comment by fergusmeiklejohn** [comment]
I restarted again and it now works :-)  I'm getting uncaught type errors with quoted code, I'm sending them from atom, so you've got all the details

**Comment by bigardone** [comment]
@msaraiva `CTRL+ALT+CMD+L` did the trick, now it works like a charm again, thank you so much :)

**Comment by msaraiva** [comment]
`CTRL+ALT+CMD+L` (or restarting Atom) is the only workaround for now. I'll take I deeper look at this problem before publishing the next release.

**Comment by msaraiva** [comment]
@lee-dohm is there a way to locally simulate a package update?

The only way I can reproduce this bug is by actually publishing and updating the package.
[Here](https://discuss.atom.io/t/how-to-register-package-installation-events-in-atom-editor/23481) you explain:
> Packages are deactivated on uninstall, activated on install, and **deactivated** and then **activated** on **update**.

I've already tried to "deactivate" and "activate" the package using `CTRL+ALT+CMD+L` as well as disabling and enabling the package. But none of them reproduce the problem. What else happens when we update a package, that differs from "disabling" and then "enabling" it again?

**Comment by lee-dohm** [comment]
What I generally do when I need to reproduce a package update bug is I use the apm feature to install a particular version like `apm install tabs-to-spaces@1.0.1`. Then I launch Atom and let the package update process handle updating to the current version.

As far as testing if a fix works, there currently isn't a good method of doing that. Though there are these changes in the works that may help:

* https://github.com/atom/apm/pull/518
* https://github.com/atom/settings-view/pull/743

I hope that helps!

**Comment by BinaryMuse** [comment]
@msaraiva Here's a bit more information about what happens down in `settings-view`'s `PackageManager::update` when you update a package:

1. It deactivates the package via `atom.packages.deactivatePackage(packageName)`
2. It unloads the package via `atom.packages.unloadPackage(packageName)`
3. It installs the update via apm
4. If the package was enabled, it re-activates it using `atom.packages.activatePackage(packageName)`

In particular, `atom.packages.deactivatePackage(...)` is interesting here because it unloads a few things and calls the `deactivate` method on the package's main module, where `CTRL+ALT+CMD+L` simply reloads the window, so there's no state shared before and after the reload (and thus doesn't accurately simulate a package update).

So to simulate the package updating you should be able to just run

```javascript
atom.packages.deactivatePackage(packageName)
atom.packages.unloadPackage(packageName)
atom.packages.activatePackage(packageName)
```

in the Atom console. If you want to simulate updating from one version to the other, you could

 1. Make Atom load the "before" version of the package (e.g. `git checkout` the version and reload Atom with `CTRL+ALT+CMD+L`)
 2. Make the necessary code changes in the package (e.g. `git checkout` the "after" version)
 3. Run the above code in the console

Hope that helps a little!

**Comment by msaraiva** [comment]
@lee-dohm and @BinaryMuse Thank you both for the detailed information. That's very helpful, indeed! I'll take a look and try it out. 

BTW, Installing packages from git urls will be a great feature.
Thanks again for all your great work!

**Comment by olivermt** [comment]
I cant get atom-elixir to start after update either, getting:

```[atom-elixir] ** (Code.LoadError) could not load /Users/oliver/.atom/packages/atom-elixir/lib/alchemist-server/lib/code/parser.exs
    (elixir) lib/code.ex:662: Code.find_file/2
    (elixir) lib/code.ex:355: Code.require_file/2
    /Users/oliver/.atom/packages/atom-elixir/lib/alchemist-server/lib/api/comp.exs:3: (file)
    (elixir) lib/code.ex:363: Code.require_file/2
    /Users/oliver/.atom/packages/atom-elixir/lib/alchemist-server/lib/server.exs:1: (file)


/Users/oliver/.atom/packages/atom-elixir/lib/server-process.coffee:75 [atom-elixir] Child process exited with code 1```

Let me know what to do to help if you need any more data or anything.

**Comment by msaraiva** [comment]
@BinaryMuse and @lee-dohm:

> In particular, atom.packages.unloadPackage(...) may be interesting here because it fully unloads the module, meaning that the next time it is reactivated, the code is read again from disk.

The above statement seems not to apply for my package. I'm probably doing something completely wrong on activate/deactivate. Every single time I update from the `settings-view`, Atom always calls the `activate` from the old package instead of the new one. The only way I could partially deal with this was by calling this ugly [hack](https://github.com/msaraiva/atom-elixir/blob/f229f7ac2f7f719ae334dce6fca5242a2fa48207/lib/atom-elixir.coffee#L70) on deactivation.

What else can I try?

**Comment by msaraiva** [comment]
This is not supposed to be an issue anymore. See https://github.com/atom/settings-view/pull/851.
