### ISSUE TITLE
Autocomplete not working properly for specific constructs

### ISSUE THREAD

**Issue by DanCouper** [msaraiva/atom-elixir#41]
If this can't be duplicated then I assume it's a conflict with another package, but after disabling other packages, I'm still seeing this behaviour:

For '@'-prefixed stuff (`@doc`, `@moduledoc`, `@type`, `@spec` *&c*), I get an extra '@', *eg*: 
<img width="292" alt="screenshot 2016-07-21 08 54 49" src="https://cloud.githubusercontent.com/assets/573694/17015720/a38124f2-4f23-11e6-9050-1de43a426ff0.png">
<img width="165" alt="screenshot 2016-07-21 08 54 59" src="https://cloud.githubusercontent.com/assets/573694/17015721/a38602a6-4f23-11e6-842b-1da740168676.png">

For 'IO' module function `IO.puts` (*just this specifically*), I get an extra `IO.`, *eg*:
<img width="413" alt="screenshot 2016-07-21 08 55 40" src="https://cloud.githubusercontent.com/assets/573694/17015723/a38aa798-4f23-11e6-9dc2-dd4001eae98f.png">
<img width="217" alt="screenshot 2016-07-21 08 55 46" src="https://cloud.githubusercontent.com/assets/573694/17015722/a386ef22-4f23-11e6-8110-0a99f6708331.png">

Just a slight annoyance,  couldn't locate anything that might be causing it withing the repo code.

**Comment by sobolevn** [comment]
The same here.

**Comment by msaraiva** [comment]
**atom-elixir** does not provide any snippets. That means those snippets are definitely coming from another package (probably language-elixir). The reason you're getting another '@' is because they were defined without the '@' prefix. As you can see from the list, there's no `@doc` but just `doc`, so if you want to use those snippets just write `doc`. The `puts` snippet has the same problem. The first one (the one not provided by atom-elixir) was defined just `puts` so it does not treat the `IO.` prefix. If you use choose the second one (the one provided by atom-elixir), you should get the expected result.

**Comment by DanCouper** [comment]
Thank you @msaraiva, sorry for cluttering up your issues.

**Comment by msaraiva** [comment]
No problem. Allowing suggestions from other packages causes confusion and that bothers me a lot too. Maybe I should create a configuration where the user could choose the preferred behaviour.
